CREATE TABLE `ride_hailing`.`RIDER_DETAILS` 
(
     `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `USER_NAME` VARCHAR(32) NOT NULL,
     `EMAIL_ADDRESS` VARCHAR(255) NOT NULL,
     `PASSWORD` VARCHAR(255) NOT NULL,
     `LATITUDE` DECIMAL(9,6) NULL DEFAULT 0,
     `LONGITUDE` DECIMAL(9,6) NULL DEFAULT 0,
     `TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
     `FIND_STATUS` INT(1) DEFAULT 0,
     `DRIVER_ID` INT(10) DEFAULT -1,
     PRIMARY KEY (`USER_ID`), 
     INDEX `USER_AUTH`(`EMAIL_ADDRESS`, `PASSWORD`)
) ENGINE = InnoDB;

CREATE TABLE `ride_hailing`.`DRIVER_DETAILS` 
(
     `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
     `USER_NAME` VARCHAR(32) NOT NULL,
     `EMAIL_ADDRESS` VARCHAR(255) NOT NULL,
     `PASSWORD` VARCHAR(255) NOT NULL,
     `LATITUDE` DECIMAL(9,6) NULL DEFAULT 0,
     `LONGITUDE` DECIMAL(9,6) NULL DEFAULT 0,
     `TIMESTAMP` TIMESTAMP NULL DEFAULT NULL,
     `IS_ACTIVE` BOOLEAN DEFAULT FALSE,
     `RIDE_STATUS` INT(1) DEFAULT 0,
     `RIDER_ID` INT(10) DEFAULT -1,
     `DEST_LAT` DECIMAL(9,6) NULL DEFAULT 0,
     `DEST_LONG` DECIMAL(9,6) NULL DEFAULT 0,
     PRIMARY KEY (`USER_ID`), 
     INDEX `USER_AUTH`(`EMAIL_ADDRESS`, `PASSWORD`)
) ENGINE = InnoDB;

/* Query for findDriver() */
SELECT USER_ID, USER_NAME, CAST(LATITUDE AS CHAR(12)) AS LATITUDE, CAST (LONGITUDE AS CHAR(12)) AS LONGITUDE FROM DRIVER_DETAILS
WHERE (LATITUDE BETWEEN %s AND %s) AND (LONGITUDE BETWEEN %s and %s)
ORDER BY LATITUDE %s + LONGITUDE - %s 

